resource_group_name = "rg-terraform-backend"
aks_cluster_name    = "keycloak-aks"
dns_prefix          = "keycloak"
vnet_name           = "keycloak-vnet"
subnet_name         = "keycloak-subnet"
ssh_key_path        = "./.ssh"
acr_name = "acrsalah"